name: Build and Deploy App

on: push

env:
  BACK_IMAGE: mistagreen/craftech-desafio-back:${{ github.sha }}
  FRONT_IMAGE: mistagreen/craftech-desafio-front:${{ github.sha }}
  DEV_NAMESPACE: dev-ns
  PROD_NAMESPACE: prod-ns
  BACK_DEPLOYMENT: backend
  FRONT_DEPLOYMENT: frontend
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: challenge-craftech-academy

jobs:
  push_and_deploy:
    name: Push images to Dockerhub and deploy them to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v2
        with:
          context: ../../5-desafio/backend
          repository: mistagreen/craftech-desafio-back
          tag_with_ref: true
          tag_with_sha: true
          tags: latest, ${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ../../5-desafio/frontend
          repository: mistagreen/craftech-desafio-front
          tag_with_ref: true
          tag_with_sha: true
          tags: latest, ${{ github.sha }}

      #Si el push tiene como referencia a la rama 'development' el deploy se
      #realiza en el namespace de desarrollo
      - name: Deploy the images to development
        if: ${{ github.ref == 'refs/heads/development' }}
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $AWS_REGION
          cluster_name: $EKS_CLUSTER_NAME
        with:
          args: |
            kubectl set image deployment $BACK_DEPLOYMENT -n $DEV_NAMESPACE $BACK_DEPLOYMENT=$BACK_IMAGE
            kubectl set image deployment $FRONT_DEPLOYMENT -n $DEV_NAMESPACE $FRONT_DEPLOYMENT=$FRONT_IMAGE
            kubectl rollout status deployment/$BACK_DEPLOYMENT -n $DEV_NAMESPACE
            kubectl rollout status deployment/$FRONT_DEPLOYMENT -n $DEV_NAMESPACE

      #Si el push tiene como referencia a la rama 'main' el deploy se
      #realiza en el namespace de producción
      - name: Deploy the images to production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $AWS_REGION
          cluster_name: $EKS_CLUSTER_NAME
        with:
          args: |
            kubectl set image deployment $BACK_DEPLOYMENT -n $PROD_NAMESPACE $BACK_DEPLOYMENT=$BACK_IMAGE
            kubectl set image deployment $FRONT_DEPLOYMENT -n $PROD_NAMESPACE $FRONT_DEPLOYMENT=$FRONT_IMAGE
            kubectl rollout status deployment/$BACK_DEPLOYMENT -n $PROD_NAMESPACE
            kubectl rollout status deployment/$FRONT_DEPLOYMENT -n $PROD_NAMESPACE
