apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s-files/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 5000
  selector:
    io.kompose.service: web-app
status:
  loadBalancer: {}
